In [1]:
import pandas as pd
import numpy as np
import xlrd
import sqlite3

In [2]:
# Import Raw Data from excel files into dataFrames
df10=pd.read_excel('mlb_odds_2010.xlsx')
df10['Year'] = 2010
df11=pd.read_excel('mlb_odds_2011.xlsx')
df11['Year'] = 2011
df12=pd.read_excel('mlb_odds_2012.xlsx')
df12['Year'] = 2012
df13=pd.read_excel('mlb_odds_2013.xlsx')
df13['Year'] = 2013
df14=pd.read_excel('mlb_odds_2014.xlsx')
df14['Year'] = 2014
df15=pd.read_excel('mlb_odds_2015.xlsx')
df15['Year'] = 2015
df16=pd.read_excel('mlb_odds_2016.xlsx')
df16['Year'] = 2016
df17=pd.read_excel('mlb_odds_2017.xlsx')
df17['Year'] = 2017
df18=pd.read_excel('mlb_odds_2018.xlsx')
df18['Year'] = 2018
df19=pd.read_excel('mlb_odds_2019.xlsx')
df19['Year'] = 2019

In [3]:
# make list of dataFrames
dfList = [df10, df11, df12, df13, df14, df15, df16, df17, df18, df19]

In [8]:
# reformat data
for df in dfList:
    try:
        dfnew=df['RL'].str.split(pat="(", n=1, expand=True)
        dfnewer = dfnew[1].str.rstrip("\)")
        df['RunLine'] = dfnew[0].apply(float)
        df['RunLineOdds'] = dfnewer.apply(int)
        df.rename({"Unnamed: 18":"OpenOUOdds", "Unnamed: 19":"OpenOUOdds", "closeou":"close_ou", "closeOU":"close_ou", "close OU":"close_ou", "Unnamed: 20":"CloseOUOdds", "Unnamed: 21":"CloseOUOdds"}, axis='columns', inplace=True)
        df.rename({"closeou":"close_ou"})
    except:
        df.rename({"Unnamed: 18":"OpenOUOdds", "Unnamed: 19":"OpenOUOdds", "closeou":"close_ou", "closeOU":"close_ou", "close OU":"close_ou", "Unnamed: 20":"CloseOUOdds", "Unnamed: 21":"CloseOUOdds"}, axis='columns', inplace=True)
        df.rename({"closeou":"close_ou"})
    df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_').str.replace('(', '').str.replace(')', '')
for df in dfList:
    colNew = []
    i = 0
    for index, row in df.iterrows():
        if index == 0:
            pass
        elif index % 2 == 0:
            i += 1
        colNew.append(i)
    df['gameno'] = colNew

In [9]:
df18.tail(10)

,date,rot,vh,team,pitcher,1st,2nd,3rd,4th,5th,...,close,rl,open_ou,openouodds,close_ou,closeouodds,year,runline,runlineodds,gameno
4918,1023,901,V,LAD,CKERSHAW-L,0,1,1,0,1,...,158.0,+1.5(-145),7.5,-110,7.5,100,2018,1.5,-145,2459
4919,1023,902,H,BOS,CSALE-L,2,0,1,0,2,...,-178.0,-1.5(+125),7.5,-110,7.5,-120,2018,-1.5,125,2459
4920,1024,903,V,LAD,HRYU-L,0,0,0,2,0,...,125.0,+1.5(-160),8.5,-119,8.5,-113,2018,1.5,-160,2460
4921,1024,904,H,BOS,DPRICE-L,0,1,0,0,3,...,-140.0,-1.5(+140),8.5,-101,8.5,-107,2018,-1.5,140,2460
4922,1026,905,V,BOS,RPORCELLO-R,0,0,0,0,0,...,155.0,+1.5(-140),7.5,-101,7.5,-120,2018,1.5,-140,2461
4923,1026,906,H,LAD,WBUEHLER-R,0,0,1,0,0,...,-175.0,-1.5(+120),7.5,-119,7.5,100,2018,-1.5,120,2461
4924,1027,907,V,BOS,ERODRIGUEZ-L,0,0,0,0,0,...,125.0,+1.5(-173),8.0,-120,8.5,-105,2018,1.5,-173,2462
4925,1027,908,H,LAD,RHILL-L,0,0,0,0,0,...,-140.0,-1.5(+150),8.0,100,8.5,-115,2018,-1.5,150,2462
4926,1028,909,V,BOS,DPRICE-L,2,0,0,0,0,...,130.0,+1.5(-170),7.5,100,7.5,-105,2018,1.5,-170,2463
4927,1028,910,H,LAD,CKERSHAW-L,1,0,0,0,0,...,-145.0,-1.5(+148),7.5,-120,7.5,-115,2018,-1.5,148,2463

In [10]:
def convt(num):
    if type(num) == str:
        num = float(num[0]) + .5
    return num
for df in dfList:
    df['close_ou'] = df['close_ou'].apply(convt)

In [33]:
df16['date_new'] = df16['date'].astype(str)
if len(df16['date_new']) == 3:
    df16['month'] = df16['date_new'][0]
    df16['day'] = df16['date_new'][1:3]
else:
    df16['month'] = df16['date_new'][0:2]
    df16['day'] = df16['date_new'][2:4]

In [22]:
# convert date format
from datetime import date



def convert_date(old_date, year):
    if len(str(old_date)) == 3:
        month = int(str(old_date)[0])
        day = int(str(old_date)[1:3])
        new_date = date(year, month, day)
    else:
        month = int(str(old_date)[0:2])
        day = int(str(old_date)[2:4])
        new_date = date(year, month, day)
    return new_date

for df in dfList:
    df['new_date'] = df['date'].apply(convert_date(df['date'], df['year']))

TypeError: 'tuple' object is not callable

In [ ]:
# create additional columns
for df in dfList:
    totRuns = []
    counter = 0
    try:
        for index, row in df.iterrows():
            if row.final == "NL":
                totRuns.append(row.final)
            elif index % 2 == 0:
                counter = 0
                counter += row.final
            else:
                counter += row.final
                totRuns.append(counter)
                totRuns.append(counter)
    except TypeError:
        print(row)
    df['totalruns'] = totRuns
    RunDif = []
    counter = 0
    try:
        for index, row in df.iterrows():
            if row.final == "NL":
                RunDif.append(row.final)
            elif index % 2 == 0:
                counter = 0
                team1 = row.final
            else:
                team2 = row.final
                dif = team1 - team2
                RunDif.append(dif)
                RunDif.append(-dif)
    except TypeError:
        print(row)
    df['rundif'] = RunDif
    winRL = []
    for index, row in df.iterrows():
        # favorite, win by more than 1.5 = True
        # favorite, win by less than 1.5 or lose = False
        # underdog, wins or loses by less than 1.5 = True
        # underdog, loses by more than 1.5 = True
        try:
            if row.runline < 0:
                if row.rundif > abs(row.runline):
                    winRL.append(True)
                else:
                    winRL.append(False)
            else:
                if row.rundif > 0 or abs(row.rundif) < row.runline:
                    winRL.append(True)
                else:
                    winRL.append(False)
        except AttributeError:
            winRL.append("NaN")
        except TypeError:
            winRL.append("NaN")
        except ValueError:
            winRL.append("NaN")
    df['winrl'] = winRL
    winTot = []
    for index, row in df.iterrows():
        try:
            if index % 2 == 0:
                if row.totalruns > row.close_ou:
                    winTot.append(True)
                else:
                    winTot.append(False)
            else:
                if row.totalruns > row.close_ou:
                    winTot.append(False)
                else:
                    winTot.append(True)
        except TypeError:
            winTot.append(True)
    df['wintotal'] = winTot

In [ ]:
df13.head(5)