In [47]:
import numpy as np
import pandas as pd
import datetime

In [15]:
data = pd.read_csv('baseball.csv', low_memory=False)

In [16]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44656 entries, 0 to 44655
Data columns (total 30 columns):
Unnamed: 0     44656 non-null int64
1st            44654 non-null float64
2nd            44654 non-null float64
3rd            44654 non-null float64
4th            44654 non-null float64
5th            44654 non-null object
6th            44652 non-null object
7th            44650 non-null object
8th            44642 non-null object
9th            44633 non-null object
close          44656 non-null float64
close_ou       44656 non-null float64
closeouodds    44656 non-null int64
date           44656 non-null object
final          44656 non-null object
open           44656 non-null int64
open_ou        44370 non-null float64
openou         286 non-null float64
openouodds     44656 non-null int64
pitcher        44613 non-null object
rot            44656 non-null int64
rundif         44656 non-null object
runline        24926 non-null float64
runlineodds    24926 non-null float64
team           44656 non-null object
totalruns      44656 non-null object
vh             44656 non-null object
winrl          24924 non-null object
wintotal       44656 non-null bool
gameno         44656 non-null int64
dtypes: bool(1), float64(10), int64(6), object(13)
memory usage: 9.9+ MB

In [18]:
data.replace('NL','0', inplace=True)

In [31]:
over_count = 0
under_count = 0
push_count = 0
for i,g in data.groupby(['gameno']):
    o_u = g[::2]
    if pd.to_numeric(o_u.totalruns.all()) > o_u.close_ou:
        over_count += 1
    elif pd.to_numeric(o_u.totalruns.all()) < o_u.close_ou:
        under_count += 1
    else:
        push_count += 1

        
print(over_count)
print(under_count)
print(push_count)

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [32]:
data.tail()

,Unnamed: 0,1st,2nd,3rd,4th,5th,6th,7th,8th,9th,...,rot,rundif,runline,runlineodds,team,totalruns,vh,winrl,wintotal,gameno
44651,281,0.0,0.0,0.0,0.0,0,2,0,0,x,...,926,1,-1.5,155.0,PHI,3,H,False,True,22316
44652,282,1.0,0.0,0.0,1.0,0,0,0,1,0,...,927,3,-1.5,148.0,TB,3,V,True,False,22317
44653,283,0.0,0.0,0.0,0.0,0,0,0,0,0,...,928,-3,1.5,-170.0,SF,3,H,False,True,22317
44654,284,0.0,0.0,0.0,0.0,0,0,1,0,0,...,929,1,-1.5,130.0,BOS,1,V,False,False,22318
44655,285,0.0,0.0,0.0,0.0,0,0,0,0,0,...,930,-1,1.5,-150.0,ARI,1,H,True,True,22318

In [42]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44656 entries, 0 to 44655
Data columns (total 30 columns):
Unnamed: 0     44656 non-null int64
1st            44654 non-null float64
2nd            44654 non-null float64
3rd            44654 non-null float64
4th            44654 non-null float64
5th            44654 non-null object
6th            44652 non-null object
7th            44650 non-null object
8th            44642 non-null object
9th            44633 non-null object
close          44656 non-null float64
close_ou       44656 non-null float64
closeouodds    44656 non-null int64
date           44656 non-null object
final          44656 non-null object
open           44656 non-null int64
open_ou        44370 non-null float64
openou         286 non-null float64
openouodds     44656 non-null int64
pitcher        44613 non-null object
rot            44656 non-null int64
rundif         44656 non-null object
runline        24926 non-null float64
runlineodds    24926 non-null float64
team           44656 non-null object
totalruns      44656 non-null object
vh             44656 non-null object
winrl          24924 non-null object
wintotal       44656 non-null bool
gameno         44656 non-null int64
dtypes: bool(1), float64(10), int64(6), object(13)
memory usage: 9.9+ MB

In [48]:
data['date'] = pd.to_datetime(data['date'])

In [58]:
date_range = data[data['date'].isin(pd.date_range('2010-06-10', '2012-06-10'))]

In [59]:
date_range

,Unnamed: 0,1st,2nd,3rd,4th,5th,6th,7th,8th,9th,...,rot,rundif,runline,runlineodds,team,totalruns,vh,winrl,wintotal,gameno
1778,1778,1.0,1.0,2.0,0.0,1,0,1,0,0,...,901,-1,NaN,NaN,SF,13,V,NaN,True,889
1779,1779,0.0,0.0,4.0,0.0,0,0,0,3,x,...,902,1,NaN,NaN,CIN,13,H,NaN,False,889
1780,1780,0.0,0.0,0.0,0.0,0,0,0,0,0,...,903,-3,NaN,NaN,SD,3,V,NaN,False,890
1781,1781,0.0,1.0,2.0,0.0,0,0,0,0,x,...,904,3,NaN,NaN,NYM,3,H,NaN,True,890
1782,1782,0.0,0.0,0.0,1.0,1,2,0,0,0,...,905,-1,NaN,NaN,CHC,9,V,NaN,True,891
1783,1783,0.0,1.0,0.0,1.0,1,1,0,0,0,...,906,1,NaN,NaN,MIL,9,H,NaN,False,891
1784,1784,0.0,2.0,0.0,0.0,1,2,0,0,0,...,907,1,NaN,NaN,HOU,9,V,NaN,True,892
1785,1785,0.0,0.0,0.0,2.0,0,0,0,2,0,...,908,-1,NaN,NaN,COL,9,H,NaN,False,892
1786,1786,0.0,0.0,0.0,2.0,5,0,0,0,4,...,909,4,NaN,NaN,ATL,18,V,NaN,True,893
1787,1787,0.0,0.0,2.0,0.0,0,0,2,3,0,...,910,-4,NaN,NaN,ARI,18,H,NaN,False,893
1788,1788,0.0,0.0,0.0,0.0,0,2,0,0,0,...,911,-2,NaN,NaN,PIT,6,V,NaN,False,894
1789,1789,0.0,0.0,0.0,2.0,1,0,0,1,x,...,912,2,NaN,NaN,WAS,6,H,NaN,True,894
1790,1790,1.0,0.0,0.0,0.0,0,0,0,0,1,...,913,2,NaN,NaN,MIA,2,V,NaN,False,895
1791,1791,0.0,0.0,0.0,0.0,0,0,0,0,0,...,914,-2,NaN,NaN,PHI,2,H,NaN,True,895
1792,1792,0.0,0.0,0.0,0.0,0,0,0,0,0,...,915,-3,NaN,NaN,DET,3,V,NaN,False,896
1793,1793,1.0,0.0,0.0,0.0,0,1,0,1,x,...,916,3,NaN,NaN,CWS,3,H,NaN,True,896
1794,1794,0.0,0.0,0.0,0.0,1,0,0,0,0,...,917,-5,NaN,NaN,LAA,7,V,NaN,False,897
1795,1795,0.0,0.0,0.0,2.0,3,0,1,0,x,...,918,5,NaN,NaN,OAK,7,H,NaN,True,897
1796,1796,4.0,1.0,0.0,0.0,0,0,0,0,2,...,919,-1,NaN,NaN,BOS,15,V,NaN,True,898
1797,1797,0.0,0.0,3.0,0.0,0,3,0,0,2,...,920,1,NaN,NaN,CLE,15,H,NaN,False,898
1798,1798,0.0,1.0,2.0,0.0,0,0,0,0,0,...,921,-1,NaN,NaN,NYY,7,V,NaN,False,899
1799,1799,2.0,0.0,0.0,0.0,1,1,0,0,x,...,922,1,NaN,NaN,BAL,7,H,NaN,True,899
1800,1800,0.0,1.0,1.0,0.0,0,0,0,1,0,...,923,1,NaN,NaN,TOR,5,V,NaN,False,900
1801,1801,0.0,1.0,0.0,0.0,0,0,0,0,1,...,924,-1,NaN,NaN,TB,5,H,NaN,True,900
1802,1802,0.0,0.0,2.0,1.0,0,0,0,0,0,...,925,-9,NaN,NaN,SEA,15,V,NaN,True,901
1803,1803,3.0,0.0,4.0,0.0,0,5,0,0,x,...,926,9,NaN,NaN,TEX,15,H,NaN,False,901
1804,1804,0.0,3.0,0.0,1.0,1,3,0,0,1,...,927,1,NaN,NaN,KC,17,V,NaN,True,902
1805,1805,0.0,0.0,0.0,1.0,0,0,5,0,2,...,928,-1,NaN,NaN,MIN,17,H,NaN,False,902
1806,1806,0.0,0.0,0.0,1.0,2,0,1,0,0,...,929,2,NaN,NaN,SD,6,V,NaN,False,903
1807,1807,0.0,2.0,0.0,0.0,0,0,0,0,0,...,930,-2,NaN,NaN,NYM,6,H,NaN,True,903
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11630,1772,1.0,1.0,0.0,0.0,0,0,0,0,3,...,901,-1,NaN,NaN,SD,11,V,NaN,True,5813
11631,1773,0.0,0.0,0.0,0.0,0,4,2,0,x,...,902,1,NaN,NaN,MIL,11,H,NaN,False,5813
11632,1774,0.0,3.0,0.0,0.0,0,0,0,0,1,...,903,-1,NaN,NaN,NYM,9,V,NaN,False,5814
11633,1775,0.0,0.0,0.0,0.0,0,0,2,2,1,...,904,1,NaN,NaN,NYY,9,H,NaN,True,5814
11634,1776,0.0,0.0,0.0,1.0,1,0,1,4,0,...,905,1,NaN,NaN,DET,13,V,NaN,True,5815
11635,1777,0.0,2.0,1.0,1.0,0,2,0,0,0,...,906,-1,NaN,NaN,CIN,13,H,NaN,False,5815
11636,1778,1.0,0.0,0.0,3.0,0,0,0,0,0,...,907,2,NaN,NaN,TB,6,V,NaN,False,5816
11637,1779,0.0,0.0,0.0,0.0,0,0,1,1,0,...,908,-2,NaN,NaN,MIA,6,H,NaN,True,5816
11638,1780,0.0,0.0,0.0,0.0,6,3,2,1,0,...,909,8,NaN,NaN,TOR,16,V,NaN,True,5817
11639,1781,0.0,2.0,2.0,0.0,0,0,0,0,0,...,910,-8,NaN,NaN,ATL,16,H,NaN,False,5817
11640,1782,0.0,0.0,0.0,0.0,0,0,1,1,0,...,911,-1,NaN,NaN,KC,5,V,NaN,False,5818
11641,1783,1.0,0.0,2.0,0.0,0,0,0,0,x,...,912,1,NaN,NaN,PIT,5,H,NaN,True,5818
11642,1784,0.0,3.0,0.0,1.0,0,0,0,0,0,...,913,-1,NaN,NaN,PHI,9,V,NaN,True,5819
11643,1785,1.0,0.0,0.0,3.0,0,0,0,0,0,...,914,1,NaN,NaN,BAL,9,H,NaN,False,5819
11644,1786,1.0,0.0,0.0,0.0,0,0,2,0,1,...,915,1,NaN,NaN,WAS,7,V,NaN,False,5820
11645,1787,0.0,0.0,1.0,1.0,0,0,1,0,0,...,916,-1,NaN,NaN,BOS,7,H,NaN,True,5820
11646,1788,0.0,2.0,0.0,0.0,2,5,0,2,0,...,917,2,NaN,NaN,HOU,20,V,NaN,True,5821
11647,1789,0.0,0.0,2.0,1.0,0,1,0,2,3,...,918,-2,NaN,NaN,CWS,20,H,NaN,False,5821
11648,1790,1.0,0.0,0.0,0.0,0,3,0,2,2,...,919,6,NaN,NaN,CHC,10,V,NaN,True,5822
11649,1791,0.0,0.0,0.0,0.0,0,0,0,0,2,...,920,-6,NaN,NaN,MIN,10,H,NaN,False,5822
11650,1792,0.0,0.0,1.0,0.0,0,0,0,0,3,...,921,3,NaN,NaN,CLE,5,V,NaN,False,5823
11651,1793,1.0,0.0,0.0,0.0,0,0,0,0,0,...,922,-3,NaN,NaN,STL,5,H,NaN,True,5823
11652,1794,4.0,2.0,0.0,3.0,0,0,0,1,0,...,923,2,NaN,NaN,LAA,18,V,NaN,True,5824
11653,1795,1.0,5.0,0.0,1.0,0,0,0,0,1,...,924,-2,NaN,NaN,COL,18,H,NaN,False,5824
11654,1796,0.0,0.0,1.0,2.0,0,2,0,0,0,...,925,5,NaN,NaN,TEX,5,V,NaN,False,5825
11655,1797,0.0,0.0,0.0,0.0,0,0,0,0,0,...,926,-5,NaN,NaN,SF,5,H,NaN,True,5825
11656,1798,0.0,0.0,0.0,2.0,0,0,1,0,0,...,927,-1,NaN,NaN,OAK,7,V,NaN,False,5826
11657,1799,3.0,0.0,0.0,0.0,1,0,0,0,x,...,928,1,NaN,NaN,ARI,7,H,NaN,True,5826
11658,1800,0.0,6.0,0.0,0.0,0,0,0,2,0,...,929,6,NaN,NaN,LAD,10,V,NaN,True,5827
11659,1801,1.0,0.0,0.0,0.0,0,0,0,0,1,...,930,-6,NaN,NaN,SEA,10,H,NaN,False,5827